### ISSUE TITLE
Retrying execution of geoserver?

### ISSUE THREAD

**Issue by carrbrpoa** [ROGUE-JCTD/rogue-chef-repo#27]
Hello,

After modifying `dna.json` to disable docs creation, I tried to run `geoshape-provision.sh`, which gives me the following error:

![geoserver](https://cloud.githubusercontent.com/assets/10212618/14749165/5d323f02-0894-11e6-887c-fce7ef356c2c.png)

Here goes the stack trace:

```
Generated at 2016-04-22 16:56:16 +0000
Chef::Exceptions::PrivateKeyMissing: I cannot read /etc/chef/validation.pem, which you told me to use to sign requests!
/usr/lib/ruby/vendor_ruby/chef/http/authenticator.rb:74:in `rescue in load_signing_key'
/usr/lib/ruby/vendor_ruby/chef/http/authenticator.rb:64:in `load_signing_key'
/usr/lib/ruby/vendor_ruby/chef/http/authenticator.rb:38:in `initialize'
/usr/lib/ruby/vendor_ruby/chef/rest.rb:63:in `new'
/usr/lib/ruby/vendor_ruby/chef/rest.rb:63:in `initialize'
/usr/lib/ruby/vendor_ruby/chef/api_client/registration.rb:111:in `new'
/usr/lib/ruby/vendor_ruby/chef/api_client/registration.rb:111:in `http_api'
/usr/lib/ruby/vendor_ruby/chef/api_client/registration.rb:93:in `create'
/usr/lib/ruby/vendor_ruby/chef/api_client/registration.rb:84:in `create_or_update'
/usr/lib/ruby/vendor_ruby/chef/api_client/registration.rb:57:in `run'
/usr/lib/ruby/vendor_ruby/chef/client.rb:380:in `register'
/usr/lib/ruby/vendor_ruby/chef/client.rb:486:in `do_run'
/usr/lib/ruby/vendor_ruby/chef/client.rb:199:in `block in run'
/usr/lib/ruby/vendor_ruby/chef/client.rb:193:in `fork'
/usr/lib/ruby/vendor_ruby/chef/client.rb:193:in `run'
/usr/lib/ruby/vendor_ruby/chef/application.rb:208:in `run_chef_client'
/usr/lib/ruby/vendor_ruby/chef/application/client.rb:312:in `block in run_application'
/usr/lib/ruby/vendor_ruby/chef/application/client.rb:304:in `loop'
/usr/lib/ruby/vendor_ruby/chef/application/client.rb:304:in `run_application'
/usr/lib/ruby/vendor_ruby/chef/application.rb:66:in `run'
/usr/bin/chef-client:25:in `<main>'
```

Any ideas?
Thanks in advance

PS: I didn't manage to install GeoShape yet.

**Comment by carrbrpoa** [comment]
Well, today after another `geoshape-provision.sh`, it worked..
